### ISSUE TITLE
js files - 404 on direct access

### ISSUE THREAD

**Issue by varun-nambiar** [amits97/naadan-chords#22]
![image](https://user-images.githubusercontent.com/1249268/93853544-a7b14b00-fcd1-11ea-8d78-2e5ad01ad1d9.png)

Direct access / refresh to any pages other than home page loads a blank page.

**Comment by amits97** [comment]
Thanks for opening the issue.

Seems weird, seems to be working fine here. This could be because of caching issues from CloudFront. I have initiated an invalidation from my end. This *should* correct the issue in a few minutes.

Let me know if the issue persists

**Comment by varun-nambiar** [comment]
Yes, cache
