### ISSUE TITLE
can't login via facebook😅, the loop goes on; 

### ISSUE THREAD

**Issue by ajmalbinnizam** [amits97/naadan-chords#49]
![image](https://user-images.githubusercontent.com/59437292/130830193-ff6eac4b-95ab-4497-abfb-13e492060d4d.png)

**Comment by ajmalbinnizam** [comment]
https://user-images.githubusercontent.com/59437292/131622276-a6aa4afd-6834-4f37-9ec7-7f618eece937.mp4

When I logged into my account, and connected my facebook; im getting logged in as a new existing user. It's not getting connected with my mail id. Is it already like that 😅

**Comment by amits97** [comment]
Apologies for the trouble. I have deleted the duplicate existing user created from FB (it was created few months back, somehow I missed it last time).

Could you please try again to connect? It should work now 😀

**Comment by ajmalbinnizam** [comment]
thanks for your time amit, its working perfect now🤟

**Comment by amits97** [comment]
No problem! Feel free to create issues if you are facing any trouble 😊
